name: Manual Trigger Example

on:
  push:
    branches:
      - 'usb'
    paths:
      - 'gpl_release.txt'
      - '.github/workflows/manual-trigger.yml'

jobs:
  fetch_deps:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: source me
      run: |
        echo "source me "
        source gpl_release.txt
        echo "buildVersion=$buildVersion"
        echo "buildNumber=$buildNumber"

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v3
      with:
        lfs: 'true'
        fetch-depth: 0

    - name: Print a message
      run: |
        echo "This is a manual trigger example"
        echo "buildVersion=$buildVersion"
        echo "buildNumber=$buildNumber"